# Generated by Django 4.0 on 2022-02-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='titulo',
            field=models.CharField(max_length=10000),
        ),
    ]
